### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by msptrooper911** [justbetter/magento2-algolia-wordpress-integration#3] opened 2019-08-04 14:25 UTC
I installed this module using composer and enabled it. But nothing changed on the Algolia search bar. I am using FishPig extension for wordpress. How do I customize the index that it should be using or how does it know? What do I do after I install it?

**Comment by royduin** [comment] 2019-08-04 14:40
Install, make sure Wordpress is running in the `/wp` directory (see [here](https://github.com/justbetter/magento2-algolia-wordpress-integration/blob/4816db8697a359c2c55c438772ab785af7666748/Helper/Entity/PageHelper.php#L44)) and reindex the pages. After that the Wordpress pages and posts (see [here](https://github.com/justbetter/magento2-algolia-wordpress-integration/blob/4816db8697a359c2c55c438772ab785af7666748/Helper/Entity/PageHelper.php#L36)) should show up in the results.

**Comment by msptrooper911** [comment] 2019-08-04 14:43
Thank you for quick response. When I try to do that. I get this error.

Warning: file_get_contents(https://dev2.qrfs.com/wp/?rest_route=/wp/v2/pages&per_page=100&page=2): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /public_html/vendor/justbetter/magento2-algolia-wordpress-integration/Helper/Entity/PageHelper.php on line 45

If I goto that REST page, it says.

{"code":"rest_post_invalid_page_number","message":"The page number requested is larger than the number of pages available.","data":{"status":400}}

Any ideas?

**Comment by royduin** [comment] 2019-08-04 14:50
Please try again with version 1.0.3 I've just created.

**Comment by msptrooper911** [comment] 2019-08-04 15:02
I tried that new file. And get this error now.


Algolia Search Pages indexer process unknown error:
Notice: Trying to get property of non-object in /public_html/vendor/justbetter/magento2-algolia-wordpress-integration/Helper/Entity/PageHelper.php on line 43

**Comment by royduin** [comment] 2019-08-04 15:06
I don't have a setup running now so I can't reproduce at the moment. Play around with the `PageHelper.php` file and let me know if you're getting it fixed so we can apply it or you can create a pull request.

**Comment by msptrooper911** [comment] 2019-08-05 21:43
I am not sure what the issue is. If I get you access to my dev site can you
try to troubleshoot?

**Comment by royduin** [comment] 2019-08-06 07:00
Send me an email and let's see what I can do for you; royduineveld at gmail

**Comment by royduin** [comment] 2019-08-08 07:36
Fixed in 1.0.4

**Closed as completed by royduin** 2019-08-08 07:36 UTC
